cert-manager:
  enabled: false
  installCRDs: true

certificates:
  ca:
    # 30y
    duration: 262800h
    # 1y
    renewBefore: 8760h
  server:
    duration: 8760h
    # 31d
    renewBefore: 744h
  client:
    duration: 8760h
    renewBefore: 744h

etcd:
  enabled: true
  replicaCount: 3
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: '{{ .Release.Name }}'
                app.kubernetes.io/name: '{{ .Chart.Name }}'
            topologyKey: topology.kubernetes.io/region
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: '{{ .Release.Name }}'
                app.kubernetes.io/name: '{{ .Chart.Name }}'
            topologyKey: topology.kubernetes.io/zone
        - weight: 2
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: '{{ .Release.Name }}'
                app.kubernetes.io/name: '{{ .Chart.Name }}'
            topologyKey: kubernetes.io/hostname
