cert-manager:
  enabled: false
  installCRDs: true

etcd:
  enabled: true
  replicaCount: 3
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: '{{ .Release.Name }}'
                app.kubernetes.io/name: '{{ .Chart.Name }}'
            topologyKey: topology.kubernetes.io/region
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: '{{ .Release.Name }}'
                app.kubernetes.io/name: '{{ .Chart.Name }}'
            topologyKey: topology.kubernetes.io/zone
        - weight: 2
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: '{{ .Release.Name }}'
                app.kubernetes.io/name: '{{ .Chart.Name }}'
            topologyKey: kubernetes.io/hostname
