kind: Issuer
apiVersion: cert-manager.io/v1
metadata:
  name: {{ include "common.names.fullname" . }}-selfsigned
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selfSigned: {}
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: {{ include "common.names.fullname" . }}-ca
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ include "common.names.fullname" . }} Certificate Authority Root
  secretName: {{ include "common.names.fullname" . }}-ca-tls
  privateKey:
    algorithm: ECDSA
    size: 521
    rotationPolicy: Never
  issuerRef:
    name: {{ include "common.names.fullname" . }}-selfsigned
    kind: Issuer
    group: cert-manager.io
  duration: {{ .Values.certificates.ca.duration | quote }}
  renewBefore: {{ .Values.certificates.ca.renewBefore | quote }}
---
kind: Issuer
apiVersion: cert-manager.io/v1
metadata:
  name: {{ include "common.names.fullname" . }}-ca
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "common.names.fullname" . }}-ca-tls
