---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: {{ include "common.names.fullname" . }}-etcd-server
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  commonName: {{ include "common.names.fullname" . }} etcd server
  secretName: {{ include "common.names.fullname" . }}-etcd-server-tls
  dnsNames:
    - {{ .Release.Name }}-etcd
    - {{ .Release.Name }}-etcd.{{ .Release.Namespace }}
    - {{ .Release.Name }}-etcd.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-etcd.{{ .Release.Namespace }}.svc.cluster.local
    - {{ .Release.Name }}-etcd-headless
    - {{ .Release.Name }}-etcd-headless.{{ .Release.Namespace }}
    - {{ .Release.Name }}-etcd-headless.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-etcd-headless.{{ .Release.Namespace }}.svc.cluster.local
{{- if gt .Values.etcd.replicaCount 0.0 }}
{{- range until (int .Values.etcd.replicaCount) }}
    - {{ $.Release.Name }}-etcd-{{ . }}
    - {{ $.Release.Name }}-etcd-{{ . }}.{{ $.Release.Namespace }}
    - {{ $.Release.Name }}-etcd-{{ . }}.{{ $.Release.Namespace }}.svc
    - {{ $.Release.Name }}-etcd-{{ . }}.{{ $.Release.Namespace }}.svc.cluster.local
    - {{ $.Release.Name }}-etcd-{{ . }}.{{ $.Release.Name }}-etcd-headless.{{ $.Release.Namespace }}
    - {{ $.Release.Name }}-etcd-{{ . }}.{{ $.Release.Name }}-etcd-headless.{{ $.Release.Namespace }}.svc
    - {{ $.Release.Name }}-etcd-{{ . }}.{{ $.Release.Name }}-etcd-headless.{{ $.Release.Namespace }}.svc.cluster.local
{{- end }}
{{- end }}
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  issuerRef:
    name: {{ include "common.names.fullname" . }}-ca
    kind: Issuer
    group: cert-manager.io
  usages:
    - signing
    - key encipherment
    - client auth
    - server auth
  duration: {{ .Values.certificates.server.duration | quote }}
  renewBefore: {{ .Values.certificates.server.renewBefore | quote }}
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: {{ include "common.names.fullname" . }}-etcd-client
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  commonName: root
  secretName: {{ include "common.names.fullname" . }}-etcd-client-tls
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  issuerRef:
    name: {{ include "common.names.fullname" . }}-ca
    kind: Issuer
    group: cert-manager.io
  usages:
    - signing
    - key encipherment
    - client auth
  duration: {{ .Values.certificates.client.duration | quote }}
  renewBefore: {{ .Values.certificates.client.renewBefore | quote }}
