kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "common.names.fullname" . }}-kube-apiserver
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    component: kube-apiserver
spec:
  replicas: {{ .Values.apiserver.replicaCount }}
  selector:
    matchLabels:
      component: kube-apiserver
  template:
    metadata:
      labels:
        component: kube-apiserver
    spec:
      containers:
        - name: kube-apiserver
